### PR TITLE
Parameters for sarufi.create_bot() & sarufi.chat()

### PR DESCRIPTION
**Pull request by bmahuvi**

### CODE REVIEW

**Comment by bmahuvi** [comment]
Hi, I tried using both, but bot `name `is missing in the `create_from_file`. For `update_from_file `is ok because you pass the `id`

**Comment by Kalebu** [comment]
> Hi, I tried using both, but bot `name `is missing in the `create_from_file`. For `update_from_file `is ok because you pass the `id`

The *name* is no longer mandatory when you do `update_from_file` because you have already created your bot so update is optional, I don't know if thats makes sense 

@bmahuvi

**Comment by bmahuvi** [comment]
I get it. Thanks

**Comment by Kalebu** [comment]
I will merge this, but I will be waiting for your pull request with the update of this

**Pull request merged**
